/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zw_mediatools_MediaTools */

#ifndef _Included_com_zw_mediatools_MediaTools
#define _Included_com_zw_mediatools_MediaTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zw_mediatools_MediaTools
 * Method:    native_exec
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zw_mediatools_MediaTools_native_1exec
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_zw_mediatools_MediaTools
 * Method:    play
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zw_mediatools_MediaTools_play
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
